### ISSUE TITLE
Docs !!!

### ISSUE THREAD

**Issue by neginsadeghi** [packetframe/infra#1]
It's about a month that me and my team are working on this to set it up as a self hosted platform to test it, there is no docs we've read the files and playbooks deeply but no success on the flow of running it.

plz for the sake of god add some docs for deployment !

**Comment by natesales** [comment]
We welcome contributions from the community and freely share code and configuration for others to learn from, but unfortunately don't have the capacity to support running a self hosted copy. Sorry!
